<?php 
 $test = 											Array(
		0=>													Array(
		0=>	Array(
	'name'=>'Creare acqua',
	'description'=>' Crea 7,4 litri/livello di acqua pura.'),
			1=>		Array(
		'name'=>'Dissanguare',
		'description'=>' Una creatura stabilizzata riprende a morire.'),
				2=>			Array(
			'name'=>'Guida',
			'description'=>' Bonus +1 a un tiro per colpire, a un tiro salvezza o a una prova di abilit&amp;agrave;.'),
					3=>				Array(
				'name'=>'Individuazione del magico',
				'description'=>' Individua incantesimi e oggetti magici nel raggio di 18 m.'),
						4=>					Array(
					'name'=>'Individuazione del veleno',
					'description'=>' Individua il veleno in una creatura o in un oggetto.'),
							5=>						Array(
						'name'=>'Lettura del magico',
						'description'=>' Per leggere pergamene e libri degli incantesimi.'),
								6=>							Array(
							'name'=>'Luce',
							'description'=>' L\'oggetto risplende come una torcia.'),
									7=>								Array(
								'name'=>'Purificare cibo e bevande',
								'description'=>' Purifica 27 dm2/livello di cibo o acqua.'),
										8=>									Array(
									'name'=>'Resistenza',
									'description'=>' Il soggetto ottiene bonus +1 ai tiri salvezza.'),
											9=>										Array(
										'name'=>'Riparare',
										'description'=>' Effettua riparazioni minori su un oggetto.'),
												10=>											Array(
											'name'=>'Stabilizzare',
											'description'=>' Stabilizza una creatura morente.'),
													11=>												Array(
												'name'=>'Virt&ugrave;',
												'description'=>' Il soggetto ottiene 1 pf temporaneo.')),
			1=>																												Array(
			0=>		Array(
		'name'=>'Anatema',
		'description'=>' I nemici subiscono penalit&amp;agrave; -1 ai tiri per colpire e ai tiri salvezza contro paura.'),
				1=>			Array(
			'name'=>'Arma magica',
			'description'=>' L\'arma ottiene bonus +1.'),
					2=>				Array(
				'name'=>'Benedire l\'acquaM',
				'description'=>' Rende l\'acqua santa.'),
						3=>					Array(
					'name'=>'Benedizione',
					'description'=>' Gli alleati ottengono bonus +1 ai tiri per colpire e bonus +1 ai tiri salvezza contro paura.'),
							4=>						Array(
						'name'=>'Comando',
						'description'=>' Un soggetto obbedisce a un ordine selezionato per 1 round.'),
								5=>							Array(
							'name'=>'Comprensione dei linguaggi',
							'description'=>' Si comprendono tutti i linguaggi scritti e parlati.'),
									6=>								Array(
								'name'=>'Contrastare elementi',
								'description'=>' Si &amp;egrave; a proprio agio in un ambiente freddo o caldo.'),
										7=>									Array(
									'name'=>'Cura ferite leggere',
									'description'=>' Cura 1d8 danni +1/livello (max +5).'),
											8=>										Array(
										'name'=>'Devastazione',
										'description'=>' Un soggetto subisce penalit&amp;agrave; -2 ai tiri per colpire, per i danni, alle prove e ai tiri salvezza.'),
												9=>											Array(
											'name'=>'Evoca mostri I',
											'description'=>' Richiama una creatura extraplanare al proprio comando.'),
													10=>												Array(
												'name'=>'Favore divino',
												'description'=>' Si ottiene bonus +1 ogni 3 livelli ai tiri per colpire e per i danni.'),
														11=>													Array(
													'name'=>'Foschia occultante',
													'description'=>' Si &amp;egrave; avvolti dalla nebbia.'),
															12=>														Array(
														'name'=>'Incuti paura',
														'description'=>' Una creatura con 5 DV o meno fugge per 1d4 round.'),
																13=>															Array(
															'name'=>'Individuazione dei non morti',
															'description'=>' Rivela non morti entro 18 m.'),
																	14=>																Array(
																'name'=>'Individuazione del bene/caos/legge/male',
																'description'=>' Rivela creature, incantesimi od oggetti dell\'allineamento selezionato.'),
																		15=>																	Array(
																	'name'=>'Infliggi ferite leggere',
																	'description'=>' Il proprio tocco infligge 1d8 danni +1/livello (max +5).'),
																			16=>																		Array(
																		'name'=>'Maledire l\'acquaM',
																		'description'=>' Rende l\'acqua sacrilega.'),
																				17=>																			Array(
																			'name'=>'Nascondersi ai non morti',
																			'description'=>' I non morti non possono percepire'),
																					18=>																				Array(
																				'name'=>'la presenza di 1 soggetto/livello.',
																				'description'=>''),
																						19=>																					Array(
																					'name'=>'Pietra magica',
																					'description'=>' Tre pietre ottengono bonus +1 all\'attacco e infliggono 1d6+1 danni.'),
																							20=>																						Array(
																						'name'=>'Protezione dal bene/caos/legge/male',
																						'description'=>' Bonus +2 alla CA e ai tiri salvezza; e in pi&amp;ugrave; protegge dall\'allineamento scelto.'),
																								21=>																							Array(
																							'name'=>'Rimuovi paura',
																							'description'=>' Sopprime la paura o fornisce bonus +4 ai tiri salvezza contro paura ad un soggetto, +1 soggetto ogni 4 livelli.'),
																									22=>																								Array(
																								'name'=>'Santuario',
																								'description'=>' Non si pu&amp;ograve; attaccare o essere attaccati dagli avversari.'),
																										23=>																									Array(
																									'name'=>'Scudo entropico',
																									'description'=>' Gli attacchi a distanza hanno una probabilit&amp;agrave; del 20% di mancare.'),
																											24=>																										Array(
																										'name'=>'Scudo della fede',
																										'description'=>' Un\'aura conferisce bonus di deviazione +2 o superiore.'),
																												25=>																											Array(
																											'name'=>'Visione della morte',
																											'description'=>' Determina le condizioni dei soggetti in fin di vita nel raggio di 9 m.')),
				2=>																																			Array(
				0=>			Array(
			'name'=>'Aiuto',
			'description'=>' Bonus +1 ai tiri per colpire e ai tiri salvezza contro paura, 1d8 pf temporanei +1/livello (max +10).'),
					1=>				Array(
				'name'=>'Allineamento imperscrutabile',
				'description'=>' Nasconde l\'allineamento per 24 ore.'),
						2=>					Array(
					'name'=>'Allineare arma',
					'description'=>' Un\'arma diventa buona, malvagia, legale o caotica.'),
							3=>						Array(
						'name'=>'Arma spirituale',
						'description'=>' Un\'arma magica che attacca di sua volont&amp;agrave;.'),
								4=>							Array(
							'name'=>'Blocca persone',
							'description'=>' Paralizza un umanoide per 1 round/livello.'),
									5=>								Array(
								'name'=>'Calmare emozioni',
								'description'=>' Calma le creature, negando gli effetti delle emozioni.'),
										6=>									Array(
									'name'=>'ConsacrareM',
									'description'=>' Riempie l\'area di energia positiva, rendendo pi&amp;ugrave; deboli i non morti.'),
											7=>										Array(
										'name'=>'Cura ferite moderate',
										'description'=>' Cura 2d8 danni +1 danno/livello (max +10).'),
												8=>											Array(
											'name'=>'DissacrareM',
											'description'=>' Riempie l\'area di energia negativa, rendendo pi&amp;ugrave; forti i non morti.'),
													9=>												Array(
												'name'=>'Estasiare',
												'description'=>' Attira l\'attenzione dei presenti entro un raggio di 30 m + 3 m/livello.'),
														10=>													Array(
													'name'=>'Evoca mostri II',
													'description'=>' Richiama una creatura extraplanare al proprio comando.'),
															11=>														Array(
														'name'=>'Forza del toro',
														'description'=>' +4 alla For per 1 minuto/livello.'),
																12=>															Array(
															'name'=>'Frantumare',
															'description'=>' Le vibrazioni sonore danneggiano oggetti o creature cristalline.'),
																	13=>																Array(
																'name'=>'Infliggi ferite moderate',
																'description'=>' Il proprio tocco infligge 2d8 danni +1/livello (max +10).'),
																		14=>																	Array(
																	'name'=>'Oscurit&agrave;',
																	'description'=>' Penombra soprannaturale nel raggio di 6 m.'),
																			15=>																		Array(
																		'name'=>'PresagioMF',
																		'description'=>' L\'incantatore apprende se un\'azione sar&amp;agrave; buona o cattiva.'),
																				16=>																			Array(
																			'name'=>'Rendere integro',
																			'description'=>' Ripara un oggetto.'),
																					17=>																				Array(
																				'name'=>'Resistenza dell\'orso',
																				'description'=>' +4 a Cos per 1 minuto/livello.'),
																						18=>																					Array(
																					'name'=>'Resistere all\'energia',
																					'description'=>' Ignora 10 (o pi&amp;ugrave;) danni per ogni attacco da uno specifico tipo di energia.'),
																							19=>																						Array(
																						'name'=>'Rimuovi paralisi',
																						'description'=>' Libera una o pi&amp;ugrave; creature dalla paralisi, o da un effetto di lentezza.'),
																								20=>																							Array(
																							'name'=>'Rintocco di morte',
																							'description'=>' Uccide una creatura morente, si ottengono 1d8 pf temporanei, +2 a For e +1 al livello dell\'incantatore.'),
																									21=>																								Array(
																								'name'=>'Riposo inviolato',
																								'description'=>' Conserva un cadavere.'),
																										22=>																									Array(
																									'name'=>'Ristorare inferiore',
																									'description'=>' Dissolve penalit&amp;agrave; magiche alle caratteristiche o cura 1d4 danni alle caratteristiche.'),
																											23=>																										Array(
																										'name'=>'Ritarda veleno',
																										'description'=>' Impedisce al veleno di nuocere al soggetto per 1 ora/livello.'),
																												24=>																											Array(
																											'name'=>'Saggezza del gufo',
																											'description'=>' +4 a Sag per 1 minuto/livello.'),
																													25=>																												Array(
																												'name'=>'Scopri trappole',
																												'description'=>' Si individuano trappole come i ladri.'),
																														26=>																													Array(
																													'name'=>'Scudo su altriF',
																													'description'=>' Si subisce met&amp;agrave; dei danni destinati a un soggetto.'),
																															27=>																														Array(
																														'name'=>'Silenzio',
																														'description'=>' Nega il suono nel raggio di 6 m.'),
																																28=>																															Array(
																															'name'=>'Splendore dell\'aquila',
																															'description'=>' +4 a Car per 1 minuto/livello.'),
																																	29=>																																Array(
																																'name'=>'Status',
																																'description'=>' Esamina la condizione e la posizione degli alleati.'),
																																		30=>																																	Array(
																																	'name'=>'Suono dirompente',
																																	'description'=>' Infligge 1d8 danni sonori ai soggetti; potrebbe stordirli.'),
																																			31=>																																		Array(
																																		'name'=>'Zona di verit&agrave;',
																																		'description'=>' I soggetti all\'interno del raggio di azione non possono mentire.')),
					3=>																																			Array(
					0=>				Array(
				'name'=>'Animare mortiM',
				'description'=>' Crea scheletri e zombi non morti.'),
						1=>					Array(
					'name'=>'Camminare sull\'acqua',
					'description'=>' Il soggetto cammina sull\'acqua come se fosse solida.'),
							2=>						Array(
						'name'=>'Cecit&agrave;/Sordit&agrave;',
						'description'=>' Rende il soggetto cieco o sordo.'),
								3=>							Array(
							'name'=>'Cerchio magico contro il bene/caos/legge/male',
							'description'=>' Come gli incantesimi protezione, ma ha un raggio di 3 m e una durata di 10 minuti/livello.'),
									4=>								Array(
								'name'=>'Contagio',
								'description'=>' Infetta il soggetto con la malattia scelta.'),
										5=>									Array(
									'name'=>'Creare cibo e acqua',
									'description'=>' Fornisce nutrimento a 3 umani (o a un cavallo)/livello.'),
											6=>										Array(
										'name'=>'Cura ferite gravi',
										'description'=>' Cura 3d8 danni +1/livello (max +15).'),
												7=>											Array(
											'name'=>'Dissolvi magie',
											'description'=>' Cancella un incantesimo o un effetto magico.'),
													8=>												Array(
												'name'=>'Epurare invisibilit&agrave;',
												'description'=>' Dissolve l\'invisibilit&amp;agrave; nel raggio di 1,5 m/livello.'),
														9=>													Array(
													'name'=>'Evoca mostri III',
													'description'=>' Richiama una creatura extraplanare al proprio comando.'),
															10=>														Array(
														'name'=>'Fiamma perenneM',
														'description'=>' Crea un torcia permanente priva di calore.'),
																11=>															Array(
															'name'=>'Fondersi nella pietra',
															'description'=>' Ci si pu&amp;ograve; immergere nella roccia con il proprio equipaggiamento.'),
																	12=>																Array(
																'name'=>'Glifo di interdizioneM',
																'description'=>' Iscrizione che infligge danni a coloro che la oltrepassano.'),
																		13=>																	Array(
																	'name'=>'Infliggi ferite gravi',
																	'description'=>' A contatto, infligge 3d8 danni +1/livello (max +15).'),
																			14=>																		Array(
																		'name'=>'Localizza oggetto',
																		'description'=>' Percepisce la direzione in cui si trova un oggetto (uno specifico o un tipo).'),
																				15=>																			Array(
																			'name'=>'Luce diurna',
																			'description'=>' Luce intensa nel raggio di 18 m.'),
																					16=>																				Array(
																				'name'=>'Luce incandescente',
																				'description'=>' Un raggio infligge 1d8 danni ogni 2 livelli (danni maggiori ai non morti).'),
																						17=>																					Array(
																					'name'=>'Mano in aiuto',
																					'description'=>' Una mano fantasma conduce un soggetto.'),
																							18=>																						Array(
																						'name'=>'Muro di vento',
																						'description'=>' Respinge frecce, piccole creature e gas.'),
																								19=>																							Array(
																							'name'=>'Occulta oggetto',
																							'description'=>'Maschera gli oggetti contro lo scrutamento.'),
																									20=>																								Array(
																								'name'=>'Oscurit&agrave; profonda',
																								'description'=>' L\'oggetto emana penombra soprannaturale nel raggio di 18 m.'),
																										21=>																									Array(
																									'name'=>'Parlare con i morti',
																									'description'=>' Un cadavere risponde a 1 domanda ogni 2 livelli.'),
																											22=>																										Array(
																										'name'=>'Preghiera',
																										'description'=>' Gli alleati ottengono bonus +1 alla maggior parte dei tiri, i nemici penalit&amp;agrave; -1.'),
																												23=>																											Array(
																											'name'=>'Protezione dall\'energia',
																											'description'=>' Assorbe 12 danni/livello da un tipo di energia.'),
																													24=>																												Array(
																												'name'=>'Respirare sott\'acqua',
																												'description'=>' Il soggetto pu&amp;ograve; respirare sott\'acqua.'),
																														25=>																													Array(
																													'name'=>'Rimuovi cecit&agrave;/sordit&agrave;',
																													'description'=>' Cura condizioni normali o magiche di cecit&amp;agrave; o sordit&amp;agrave;.'),
																															26=>																														Array(
																														'name'=>'Rimuovi malattia',
																														'description'=>' Cura tutte le malattie che affliggono il soggetto.'),
																																27=>																															Array(
																															'name'=>'Rimuovi maledizione',
																															'description'=>' Libera un oggetto o una persona da una maledizione.'),
																																	28=>																																Array(
																																'name'=>'Scagliare maledizione',
																																'description'=>' -6 a un punteggio di caratteristica, penalit&amp;agrave; -4 ai tiri per colpire, ai tiri salvezza e alle prove; o probabilit&amp;agrave; del 50% di perdere ogni azione.'),
																																		29=>																																	Array(
																																	'name'=>'Scolpire pietra',
																																	'description'=>' Plasma la pietra in qualsiasi forma.'),
																																			30=>																																		Array(
																																		'name'=>'Veste magica',
																																		'description'=>' Un\'armatura o uno scudo ottiene bonus di potenziamento +1 ogni 4 livelli.')),
						4=>																																Array(
						0=>					Array(
					'name'=>'Alleato planare inferioreM',
					'description'=>' Scambio di servigi con una creatura extraplanare con 6 DV.'),
							1=>						Array(
						'name'=>'Ancora dimensionale',
						'description'=>' Impedisce il viaggio extradimensionale.'),
								2=>							Array(
							'name'=>'Arma magica superiore',
							'description'=>' Bonus +1 ogni 4 livelli (max +5).'),
									3=>								Array(
								'name'=>'Camminare nell\'aria',
								'description'=>' Il soggetto cammina nell\'aria come se fosse solida (sale a un\'angolazione di 45th).'),
										4=>									Array(
									'name'=>'Collera dell\'ordine',
									'description'=>' Danneggia e frastorna le creature caotiche (1d8 danni ogni 2 livelli).'),
											5=>										Array(
										'name'=>'Congedo',
										'description'=>' Costringe una creatura a tornare al suo piano nativo.'),
												6=>											Array(
											'name'=>'Controllare acqua',
											'description'=>' Solleva o abbassa masse d\'acqua.'),
													7=>												Array(
												'name'=>'Cura ferite critiche',
												'description'=>' Cura 4d8 danni +1/livello (max +20).'),
														8=>													Array(
													'name'=>'DivinazioneM',
													'description'=>' Fornisce suggerimenti utili su azioni specificamente proposte.'),
															9=>														Array(
														'name'=>'Evoca mostri IV',
														'description'=>' Richiama una creatura extraplanare al proprio comando.'),
																10=>															Array(
															'name'=>'Immunit&agrave; agli incantesimi',
															'description'=>' Il soggetto &amp;egrave; immune a un incantesimo ogni 4 livelli.'),
																	11=>																Array(
																'name'=>'Infliggi ferite critiche',
																'description'=>' A contatto, infligge 4d8 danni +1/livello (max +20).'),
																		12=>																	Array(
																	'name'=>'Influenza sacrilega',
																	'description'=>' Danneggia e rende malate le creature buone (1d8 danni ogni 2 livelli).'),
																			13=>																		Array(
																		'name'=>'Infondere capacit&agrave; magiche',
																		'description'=>' Trasferisce gli incantesimi a un soggetto.'),
																				14=>																			Array(
																			'name'=>'Interdizione alla morte',
																			'description'=>' Concede immunit&amp;agrave; agli incantesimi di morte e agli effetti di energia negativa.'),
																					15=>																				Array(
																				'name'=>'Inviare',
																				'description'=>' Riferisce un breve messaggio ovunque, all\'istante.'),
																						16=>																					Array(
																					'name'=>'Libert&agrave; di movimento',
																					'description'=>' Il soggetto si muove liberamente nonostante gli impedimenti.'),
																							17=>																						Array(
																						'name'=>'Linguaggi',
																						'description'=>' Permette di parlare e comprendere qualsiasi linguaggio.'),
																								18=>																							Array(
																							'name'=>'Martello del caos',
																							'description'=>' Danneggia e rallenta le creature legali (1d8 danni ogni 2 livelli).'),
																									19=>																								Array(
																								'name'=>'Neutralizza veleno',
																								'description'=>' Rende immune al veleno un soggetto, disintossica dal veleno in o su un soggetto.'),
																										20=>																									Array(
																									'name'=>'Parassiti giganti',
																									'description'=>' Trasforma millepiedi, scorpioni o ragni in parassiti giganti.'),
																											21=>																										Array(
																										'name'=>'Potere divino',
																										'description'=>' L\'incantatore ottiene bonus di attacco e 1 pf/livello.'),
																												22=>																											Array(
																											'name'=>'Punizione sacra',
																											'description'=>' Danneggia e acceca le creature malvagie (1d8 danni ogni 2 livelli).'),
																													23=>																												Array(
																												'name'=>'Respingere parassiti',
																												'description'=>' Insetti, ragni e altri parassiti rimangono a una distanza di 3 m.'),
																														24=>																													Array(
																													'name'=>'RistorareM',
																													'description'=>' Ripristina il risucchio di livelli e di punteggi di caratteristica.'),
																															25=>																														Array(
																														'name'=>'Rivela bugie',
																														'description'=>' Rivela le menzogne deliberate.'),
																																26=>																															Array(
																															'name'=>'Veleno',
																															'description'=>' A contatto, infligge 1d3 danni a Cos, 1/round per 6 round.')),
							5=>																															Array(
							0=>						Array(
						'name'=>'Arma distruttiva',
						'description'=>' Un\'arma da mischia distrugge i non morti.'),
								1=>							Array(
							'name'=>'Colpo infuocato',
							'description'=>' Colpisce i nemici con un fuoco divino (1d6 danni/livello).'),
									2=>								Array(
								'name'=>'Comando superiore',
								'description'=>' Come comando, ma influenza 1 soggetto/livello.'),
										3=>									Array(
									'name'=>'ComunioneM',
									'description'=>' Una divinit&amp;agrave; risponde con un s&amp;igrave; o un no a 1 domanda/livello.'),
											4=>										Array(
										'name'=>'Cura ferite leggere di massa',
										'description'=>' Cura 1d8 danni +1/livello a 1 soggetto/livello.'),
												5=>											Array(
											'name'=>'Dissolvi il bene/caos/legge/male',
											'description'=>' Bonus +4 contro gli attacchi.'),
													6=>												Array(
												'name'=>'Distruggere viventi',
												'description'=>' Un attacco di contatto infligge 12d6 danni +1/livello.'),
														7=>													Array(
													'name'=>'EspiazioneFM',
													'description'=>' Rimuove il fardello dei misfatti dal soggetto e inverte il cambio di allineamento dovuto a magie.'),
															8=>														Array(
														'name'=>'Evoca mostri V',
														'description'=>' Richiama una creatura extraplanare al proprio comando.'),
																9=>															Array(
															'name'=>'Giusto potere',
															'description'=>' Si aumenta la propria taglia e si ottiene bonus combattimento.'),
																	10=>																Array(
																'name'=>'Infliggi ferite leggere di massa',
																'description'=>' Infligge 1d8 danni +1/livello a 1 soggetto/livello.'),
																		11=>																	Array(
																	'name'=>'Muro di pietra',
																	'description'=>' Crea un muro di pietra che pu&amp;ograve; essere plasmato.'),
																			12=>																		Array(
																		'name'=>'Piaga degli insetti',
																		'description'=>' Sciami di vespe attaccano le creature.'),
																				13=>																			Array(
																			'name'=>'ProfanareM',
																			'description'=>' Rende una locazione sacrilega.'),
																					14=>																				Array(
																				'name'=>'Resistenza agli incantesimi',
																				'description'=>' Il soggetto ottiene RI 12 + livello.'),
																						15=>																					Array(
																					'name'=>'Respiro di vita',
																					'description'=>' Cura 5d8 danni + 1/livello e ridona la vita a creature appena uccise.'),
																							16=>																						Array(
																						'name'=>'Rianimare mortiM',
																						'description'=>' Riporta in vita un soggetto che &amp;egrave; morto da 1 giorno/livello.'),
																								17=>																							Array(
																							'name'=>'SantificareM',
																							'description'=>' Consacra una locazione.'),
																									18=>																								Array(
																								'name'=>'Spezzare incantamento',
																								'description'=>' Libera i soggetti da ammaliamenti, alterazioni, maledizioni.'),
																										19=>																									Array(
																									'name'=>'ScrutareF',
																									'description'=>' Spia soggetti a distanza.'),
																											20=>																										Array(
																										'name'=>'Sigillo di giustizia',
																										'description'=>' Determina un\'azione che attiver&amp;agrave; una maledizione sul soggetto.'),
																												21=>																											Array(
																											'name'=>'Simbolo di doloreM',
																											'description'=>' Runa che devasta le creature vicine con dolori indicibili.'),
																													22=>																												Array(
																												'name'=>'Simbolo di sonnoM',
																												'description'=>' Runa che fa cadere le creature vicine in un sonno catatonico.'),
																														23=>																													Array(
																													'name'=>'Spostamento planareF',
																													'description'=>' Fino a 8 soggetti viaggiano su un altro piano.'),
																															24=>																														Array(
																														'name'=>'Visione del veroM',
																														'description'=>' Permette di vedere tutte le cose per quello che sono veramente.')),
								6=>																																	Array(
								0=>							Array(
							'name'=>'Alleato planareM',
							'description'=>' Come alleato planare inferiore, ma fino a 12 DV.'),
									1=>								Array(
								'name'=>'Animare oggetti',
								'description'=>' Oggetti attaccano i nemici.'),
										2=>									Array(
									'name'=>'Banchetto degli eroi',
									'description'=>' Cibo per 1 creatura/livello, cura e fornisce bonus di combattimento.'),
											3=>										Array(
										'name'=>'Barriera di lame',
										'description'=>' Una cortina di lame infligge 1d6 danni/livello.'),
												4=>											Array(
											'name'=>'Camminare nel vento',
											'description'=>' Insieme ai propri alleati si diventa inconsistenti e si pu&amp;ograve; viaggiare velocemente.'),
													5=>												Array(
												'name'=>'Costrizione/cerca',
												'description'=>' Come costrizione inferiore, ma influenza qualsiasi creatura.'),
														6=>													Array(
													'name'=>'Creare non mortiM',
													'description'=>' Per creare ghoul, ghast, mummie o mohrg.'),
															7=>														Array(
														'name'=>'Cura ferite moderate di massa',
														'description'=>' Cura 2d8 danni +1/livello (max +30) a 1 soggetto/livello.'),
																8=>															Array(
															'name'=>'Dissolvi magie superiore',
															'description'=>' Come dissolvi magie, ma con bersagli multipli.'),
																	9=>																Array(
																'name'=>'Esilio',
																'description'=>' Bandisce 2 DV/livello di creature extraplanari.'),
																		10=>																	Array(
																	'name'=>'Evoca mostri VI',
																	'description'=>' Richiama una creatura extraplanare al proprio comando.'),
																			11=>																		Array(
																		'name'=>'Ferire',
																		'description'=>' Infligge 10 danni/livello al bersaglio.'),
																				12=>																			Array(
																			'name'=>'Forza del toro di massa',
																			'description'=>' Come forza del toro, ma influenza 1 soggetto/livello.'),
																					13=>																				Array(
																				'name'=>'Glifo di interdizione superioreM',
																				'description'=>' Come glifo di interdizione, ma fino a 10d8 danni o un incantesimo di 6th livello.'),
																						14=>																					Array(
																					'name'=>'Guarigione',
																					'description'=>' Cura 10 danni/livello, tutte le malattie e le condizioni mentali.'),
																							15=>																						Array(
																						'name'=>'Guscio anti-vita',
																						'description'=>' Un campo di 3 m respinge le creature viventi.'),
																								16=>																							Array(
																							'name'=>'Infliggi ferite moderate di massa',
																							'description'=>' Infligge 2d8 danni +1/livello a 1 soggetto/livello.'),
																									17=>																								Array(
																								'name'=>'Non morto a mortoM',
																								'description'=>' Distrugge 1d4 DV/livello di non morti (max 20d4).'),
																										18=>																									Array(
																									'name'=>'Parola del ritiro',
																									'description'=>' Teletrasporta indietro ad un posto designato.'),
																											19=>																										Array(
																										'name'=>'ProibizioneM',
																										'description'=>' Blocca i viaggi planari, infligge danni alle creature di un altro allineamento.'),
																												20=>																											Array(
																											'name'=>'Resistenza dell\'orso di massa',
																											'description'=>' Come resistenza dell\'orso, ma influenza 1 soggetto/livello.'),
																													21=>																												Array(
																												'name'=>'Saggezza del gufo di massa',
																												'description'=>' Come saggezza del gufo, ma influenza 1 soggetto/livello.'),
																														22=>																													Array(
																													'name'=>'Scopri il percorso',
																													'description'=>' Indica la via pi&amp;ugrave; diretta verso una locazione.'),
																															23=>																														Array(
																														'name'=>'Simbolo di pauraM',
																														'description'=>' Runa che fa cadere le creature vicine in preda al panico.'),
																																24=>																															Array(
																															'name'=>'Simbolo di persuasioneM',
																															'description'=>' Runa che rende le creature vicine soggette a charme.'),
																																	25=>																																Array(
																																'name'=>'Splendore dell\'aquila di massa',
																																'description'=>' Come splendore dell\'aquila, ma influenza 1 soggetto/livello.')),
									7=>																										Array(
									0=>								Array(
								'name'=>'Blasfemia',
								'description'=>' Uccide, paralizza, indebolisce o frastorna i soggetti non malvagi.'),
										1=>									Array(
									'name'=>'Controllare tempo atmosferico',
									'description'=>' Cambia il tempo atmosferico in un\'area.'),
											2=>										Array(
										'name'=>'Cura ferite gravi di massa',
										'description'=>' Cura 3d8 danni +1/livello a 1 soggetto/livello.'),
												3=>											Array(
											'name'=>'Dettame',
											'description'=>' Uccide, paralizza, rende barcollante o assorda i soggetti non legali.'),
													4=>												Array(
												'name'=>'DistruzioneF',
												'description'=>' Uccide il soggetto e ne distrugge i resti.'),
														5=>													Array(
													'name'=>'Evoca mostri VII',
													'description'=>' Richiama una creatura extraplanare al proprio comando.'),
															6=>														Array(
														'name'=>'Infliggi ferite gravi di massa',
														'description'=>' Infligge 3d8 danni +1/livello a 1 soggetto/livello.'),
																7=>															Array(
															'name'=>'Parola del caos',
															'description'=>' Uccide, rende confusi, stordisce o assorda i soggetti non caotici.'),
																	8=>																Array(
																'name'=>'Parola sacra',
																'description'=>' Uccide, paralizza, acceca o assorda i soggetti non buoni.'),
																		9=>																	Array(
																	'name'=>'Repulsione',
																	'description'=>' Le creature non possono avvicinarsi.'),
																			10=>																		Array(
																		'name'=>'ResurrezioneM',
																		'description'=>' Fa risorgere interamente il soggetto morto.'),
																				11=>																			Array(
																			'name'=>'RifugioM',
																			'description'=>' Altera un oggetto per trasportare a s&eacute; il suo possessore.'),
																					12=>																				Array(
																				'name'=>'Rigenerazione',
																				'description'=>' Gli arti recisi di un soggetto ricrescono, cura 4d8 danni +1/livello (max +35).'),
																						13=>																					Array(
																					'name'=>'Ristorare superioreM',
																					'description'=>' Come ristorare, ma ripristina tutti i punteggi di caratteristica.'),
																							14=>																						Array(
																						'name'=>'Scrutare superiore',
																						'description'=>' Come scrutare, ma pi&amp;ugrave; velocemente e a lungo.'),
																								15=>																							Array(
																							'name'=>'Simbolo di debolezzaM',
																							'description'=>' Runa che indebolisce le creature.'),
																									16=>																								Array(
																								'name'=>'Simbolo di stordimentoM',
																								'description'=>' Runa che stordisce le creature vicine.'),
																										17=>																									Array(
																									'name'=>'Transizione eterea',
																									'description'=>' L\'incantatore diventa etereo per 1 round/livello.')),
										8=>																										Array(
										0=>									Array(
									'name'=>'Alleato planare superioreM',
									'description'=>' Come alleato planare inferiore, ma fino a 18 DV.'),
											1=>										Array(
										'name'=>'Aura sacraF',
										'description'=>' Bonus +4 alla CA, bonus di resistenza +4 e RI 25 contro incantesimi del male.'),
												2=>											Array(
											'name'=>'Aura sacrilegaF',
											'description'=>' Bonus +4 alla CA, bonus di resistenza +4 e RI 25 contro incantesimi del bene.'),
													3=>												Array(
												'name'=>'Campo anti-magia',
												'description'=>' Nega la magia nel raggio di 3 m.'),
														4=>													Array(
													'name'=>'Creare non morti superioriM',
													'description'=>' Per creare ombre, wraith, spettri o divoratori.'),
															5=>														Array(
														'name'=>'Cura ferite critiche di massa',
														'description'=>' Cura 4d8 danni +1/livello a 1 soggetto/livello.'),
																6=>															Array(
															'name'=>'Evoca mostri VIII',
															'description'=>' Richiama una creatura extraplanare al proprio comando.'),
																	7=>																Array(
																'name'=>'Immunit&agrave; agli incantesimi superiore',
																'description'=>' Come immunit&amp;agrave; agli incantesimi, ma fino a incantesimi di 8th livello.'),
																		8=>																	Array(
																	'name'=>'Infliggi ferite critiche di massa',
																	'description'=>' Infligge 4d8 danni +1/livello a 1 soggetto/livello.'),
																			9=>																		Array(
																		'name'=>'Mantello del caosF',
																		'description'=>' Bonus +4 alla CA, bonus di resistenza +4 e RI 25 contro incantesimi della legge.'),
																				10=>																			Array(
																			'name'=>'Rivela locazioni',
																			'description'=>' Locazione esatta di una creatura o di un oggetto.'),
																					11=>																				Array(
																				'name'=>'Scudo della leggeF',
																				'description'=>' Bonus +4 alla CA, bonus di resistenza +4 e RI 25 contro incantesimi del caos.'),
																						12=>																					Array(
																					'name'=>'Serratura dimensionale',
																					'description'=>' Teletrasporto e viaggi interplanari bloccati per 1 giorno/livello.'),
																							13=>																						Array(
																						'name'=>'Simbolo di demenzaM',
																						'description'=>' Runa che rende dementi le creature vicine.'),
																								14=>																							Array(
																							'name'=>'Simbolo di morteM',
																							'description'=>' Runa che uccide le creature vicine.'),
																									15=>																								Array(
																								'name'=>'Tempesta di fuoco',
																								'description'=>' Infligge 1d6 danni da fuoco/livello.'),
																										16=>																									Array(
																									'name'=>'Terremoto',
																									'description'=>' Un tremito intenso scuote la terra in un raggio di 24 m.')),
											9=>																					Array(
											0=>										Array(
										'name'=>'Evoca mostri IX',
										'description'=>' Richiama una creatura extraplanare al proprio comando.'),
												1=>											Array(
											'name'=>'Forma eterea',
											'description'=>' Per viaggiare sul Piano Etereo con i compagni.'),
													2=>												Array(
												'name'=>'Guarigione di massa',
												'description'=>' Come guarigione, ma su 1 soggetto/livello.'),
														3=>													Array(
													'name'=>'Implosione',
													'description'=>' Infligge 10 danni/livello ad 1 creatura/round.'),
															4=>														Array(
														'name'=>'Legare animaF',
														'description'=>' Intrappola un\'anima appena morta per impedirne la resurrezione.'),
																5=>															Array(
															'name'=>'MiracoloM',
															'description'=>' Richiede l\'intervento di una divinit&amp;agrave;.'),
																	6=>																Array(
																'name'=>'PortaleM',
																'description'=>' Collega due piani per viaggiare o per evocare creature.'),
																		7=>																	Array(
																	'name'=>'Proiezione astraleM',
																	'description'=>' Si viene proiettati insieme ai propri compagni sul Piano Astrale.'),
																			8=>																		Array(
																		'name'=>'Resurrezione puraM',
																		'description'=>' Come resurrezione, ma non sono necessari i resti.'),
																				9=>																			Array(
																			'name'=>'Risucchio di energia',
																			'description'=>' Il soggetto ottiene 2d4 livelli negativi.'),
																					10=>																				Array(
																				'name'=>'Tempesta di vendetta',
																				'description'=>' Tempesta di pioggia acida, fulmini e grandine.'))); 
 echo json_encode($test); ?>