<?php 
 $test = 											Array(
		0=>														Array(
		0=>	Array(
	'name'=>'Conoscere direzione',
	'description'=>' Si riesce a individuare il nord.'),
			1=>		Array(
		'name'=>'Creare acqua',
		'description'=>' Crea 7,4 litri/livello di acqua pura.'),
				2=>			Array(
			'name'=>'Guida',
			'description'=>' Bonus +1 a un tiro per colpire, a un tiro salvezza o a una prova di abilit&amp;agrave;.'),
					3=>				Array(
				'name'=>'Individuazione del magico',
				'description'=>' Individua incantesimi e oggetti magici nel raggio di 18 m.'),
						4=>					Array(
					'name'=>'Individuazione del veleno',
					'description'=>' Individua il veleno in una creatura o in un oggetto.'),
							5=>						Array(
						'name'=>'Lampo',
						'description'=>' Abbaglia una creatura (penalit&amp;agrave; -1 ai tiri per colpire).'),
								6=>							Array(
							'name'=>'Lettura del magico',
							'description'=>' Per leggere pergamene e libri degli incantesimi.'),
									7=>								Array(
								'name'=>'Luce',
								'description'=>' L\'oggetto risplende come una torcia.'),
										8=>									Array(
									'name'=>'Purificare cibo e bevande',
									'description'=>' Purifica 27 dm2/livello di cibo o acqua.'),
											9=>										Array(
										'name'=>'Resistenza',
										'description'=>' Il soggetto ottiene bonus +1 ai tiri salvezza.'),
												10=>											Array(
											'name'=>'Riparare',
											'description'=>' Effettua riparazioni minori su un oggetto.'),
													11=>												Array(
												'name'=>'Stabilizzare',
												'description'=>' Una creatura che sta morendo si stabilizza.'),
														12=>													Array(
													'name'=>'Virt&ugrave;',
													'description'=>' Il soggetto ottiene 1 pf temporaneo.')),
			1=>																						Array(
			0=>		Array(
		'name'=>'Bacche benefiche',
		'description'=>' 2d4 bacche, ciascuna cura 1 pf (max 8 pf /24 ore).'),
				1=>			Array(
			'name'=>'Calmare animali',
			'description'=>' Calma 2d4 + livello DV di animali.'),
					2=>				Array(
				'name'=>'Charme su animali',
				'description'=>' Rende un animale amichevole.'),
						3=>					Array(
					'name'=>'Contrastare elementi',
					'description'=>' Si &amp;egrave; a proprio agio in un ambiente freddo o caldo.'),
							4=>						Array(
						'name'=>'Cura ferite leggere',
						'description'=>' Cura 1d8 danni +1/livello (max +5).'),
								5=>							Array(
							'name'=>'Evoca alleato naturale I',
							'description'=>' Richiama una creatura al proprio comando.'),
									6=>								Array(
								'name'=>'Foschia occultante',
								'description'=>' Si &amp;egrave; avvolti dalla nebbia.'),
										7=>									Array(
									'name'=>'Individuazione di animali o vegetali',
									'description'=>' Individua specie di animali o vegetali.'),
											8=>										Array(
										'name'=>'Individuazione di calappi e trabocchetti',
										'description'=>' Rivela trappole naturali o primitive.'),
												9=>											Array(
											'name'=>'Intralciare',
											'description'=>' Le piante avviluppano chiunque in un raggio di 12 m.'),
													10=>												Array(
												'name'=>'Luminescenza',
												'description'=>' Delinea i soggetti con un alone di luce, nega sfocatura, occultamenti e simili.'),
														11=>													Array(
													'name'=>'Nascondersi agli animali',
													'description'=>' Gli animali non riescono a percepire 1 soggetto/livello.'),
															12=>														Array(
														'name'=>'Parlare con gli animali',
														'description'=>' Si pu&amp;ograve; comunicare con gli animali.'),
																13=>															Array(
															'name'=>'Passare senza tracce',
															'description'=>' 1 soggetto/livello non lascia tracce.'),
																	14=>																Array(
																'name'=>'Passo veloce',
																'description'=>' Aumenta la propria velocit&amp;agrave; di 3 m.'),
																		15=>																	Array(
																	'name'=>'Pietra magica',
																	'description'=>' Tre pietre ottengono bonus +1 all\'attacco e infliggono 1d6+1 danni.'),
																			16=>																		Array(
																		'name'=>'Produrre fiamma',
																		'description'=>' 1d6 danni +1/livello, a contatto o lanciata.'),
																				17=>																			Array(
																			'name'=>'Randello incantato',
																			'description'=>' Un randello o un bastone ferrato diventano un\'arma +1 (1d10 danni) per 1 minuto/livello.'),
																					18=>																				Array(
																				'name'=>'Saltare',
																				'description'=>' Il soggetto ottiene un bonus alle prove di Acrobazia.'),
																						19=>																					Array(
																					'name'=>'Zanna magica',
																					'description'=>' Un\'arma naturale del soggetto ottiene bonus +1 ai tiri per colpire e per i danni.')),
				2=>																													Array(
				0=>			Array(
			'name'=>'Ammorbidire terra e pietra',
			'description'=>' Trasforma la pietra in argilla o la terra in sabbia e fango.'),
					1=>				Array(
				'name'=>'Animale messaggero',
				'description'=>' Invia un animale Minuscolo in un posto specifico.'),
						2=>					Array(
					'name'=>'Blocca animali',
					'description'=>' Paralizza un animale per 1 round/livello.'),
							3=>						Array(
						'name'=>'Deformare legno',
						'description'=>' Piega il legno.'),
								4=>							Array(
							'name'=>'Evoca alleato naturale II',
							'description'=>' Richiama una creatura al proprio comando.'),
									5=>								Array(
								'name'=>'Evoca sciame',
								'description'=>' Richiama uno sciame di pipistrelli, ratti o ragni.'),
										6=>									Array(
									'name'=>'Folata di vento',
									'description'=>' Porta via o butta a terra le creature pi&amp;ugrave; piccole.'),
											7=>										Array(
										'name'=>'Forma arborea',
										'description'=>' Si assume l\'aspetto di un albero per 1 ora/livello.'),
												8=>											Array(
											'name'=>'Forza del toro',
											'description'=>' Bonus +4 a For per 1 minuto/livello.'),
													9=>												Array(
												'name'=>'Gelare il metallo',
												'description'=>' Il metallo freddo danneggia chi lo tocca.'),
														10=>													Array(
													'name'=>'Grazia del gatto',
													'description'=>' Bonus +4 a Des per 1 minuto/livello.'),
															11=>														Array(
														'name'=>'Lama infuocata',
														'description'=>' Un attacco di contatto infligge 1d8 danni +1 ogni 2 livelli.'),
																12=>															Array(
															'name'=>'Movimenti del ragno',
															'description'=>' Conferisce la capacit&amp;agrave; di camminare sulle pareti e sui soffitti.'),
																	13=>																Array(
																'name'=>'Nube di nebbia',
																'description'=>' Un banco di nebbia ostacola la visuale.'),
																		14=>																	Array(
																	'name'=>'Trance animale',
																	'description'=>' Affascina 2d6 DV di animali.'),
																			15=>																		Array(
																		'name'=>'Pelle coriacea',
																		'description'=>' Concede bonus di potenziamento +2 (o superiore) all\'armatura naturale.'),
																				16=>																			Array(
																			'name'=>'Resistenza dell\'orso',
																			'description'=>' Bonus +4 a Cos per 1 minuto/livello.'),
																					17=>																				Array(
																				'name'=>'Resistere all\'energia',
																				'description'=>' Ignora 10 (o pi&amp;ugrave;) danni per ogni attacco da uno specifico tipo di energia.'),
																						18=>																					Array(
																					'name'=>'Ridurre animali',
																					'description'=>' Rimpicciolisce un animale consenziente.'),
																							19=>																						Array(
																						'name'=>'Riscaldare il metallo',
																						'description'=>' Rende il metallo talmente caldo da danneggiare chi lo tocca.'),
																								20=>																							Array(
																							'name'=>'Ristorare inferiore',
																							'description'=>' Dissolve penalit&amp;agrave; magiche alle caratteristiche o cura 1d4 danni alle caratteristiche.'),
																									21=>																								Array(
																								'name'=>'Ritarda veleno',
																								'description'=>' Impedisce al veleno di nuocere al soggetto per 1 ora/livello.'),
																										22=>																									Array(
																									'name'=>'Saggezza del gufo',
																									'description'=>' Bonus +4 a Sag per 1 minuto/livello.'),
																											23=>																										Array(
																										'name'=>'Scolpire legno',
																										'description'=>' Ricrea gli oggetti in legno nel modo desiderato.'),
																												24=>																											Array(
																											'name'=>'Sfera infuocata',
																											'description'=>' Una palla di fuoco che infligge 3d6 danni.'),
																													25=>																												Array(
																												'name'=>'Trappola di fuocoM',
																												'description'=>' Gli oggetti aperti infliggono 1d4 danni +1/livello.')),
					3=>																										Array(
					0=>				Array(
				'name'=>'Calappio',
				'description'=>' Crea una trappola magica.'),
						1=>					Array(
					'name'=>'Contagio',
					'description'=>' Infetta il soggetto con la malattia scelta.'),
							2=>						Array(
						'name'=>'Crescita di spine',
						'description'=>' Le creature nell\'area subiscono 1d4 danni e possono essere rallentate.'),
								3=>							Array(
							'name'=>'Crescita vegetale',
							'description'=>' Fa crescere la vegetazione e migliora i raccolti.'),
									4=>								Array(
								'name'=>'Cura ferite moderate',
								'description'=>' Cura 2d8 danni +1/livello (max +10).'),
										5=>									Array(
									'name'=>'Dominare animali',
									'description'=>' L\'animale assoggettato obbedisce a comandi mentali silenziosi.'),
											6=>										Array(
										'name'=>'Estinguere fuoco',
										'description'=>' Estingue fuochi.'),
												7=>											Array(
											'name'=>'Evoca alleato naturale III',
											'description'=>' Richiama una creatura al proprio comando.'),
													8=>												Array(
												'name'=>'Fondersi nella pietra',
												'description'=>' Ci si immerge nella roccia con il proprio equipaggiamento.'),
														9=>													Array(
													'name'=>'Invocare il fulmine',
													'description'=>' Fa scendere dei fulmini (3d6 danni per fulmine) dal cielo.'),
															10=>														Array(
														'name'=>'Luce diurna',
														'description'=>' Luce intensa nel raggio di 18 m.'),
																11=>															Array(
															'name'=>'Muro di vento',
															'description'=>' Respinge frecce, piccole creature e gas.'),
																	12=>																Array(
																'name'=>'Neutralizza veleno',
																'description'=>' Rende immune al veleno un soggetto, disintossica dal veleno in o su un soggetto.'),
																		13=>																	Array(
																	'name'=>'Parlare con i vegetali',
																	'description'=>' Si pu&amp;ograve; comunicare con i vegetali normali e con le creature vegetali.'),
																			14=>																		Array(
																		'name'=>'Protezione dall\'energia',
																		'description'=>' Assorbe 12 danni/livello da un tipo di energia.'),
																				15=>																			Array(
																			'name'=>'Respirare sott\'acqua',
																			'description'=>' Il soggetto pu&amp;ograve; respirare sott\'acqua.'),
																					16=>																				Array(
																				'name'=>'Rimpicciolire vegetali',
																				'description'=>' Riduce la taglia o inaridisce la crescita dei vegetali naturali.'),
																						17=>																					Array(
																					'name'=>'Rimuovi malattia',
																					'description'=>' Cura le malattie che affliggono un soggetto.'),
																							18=>																						Array(
																						'name'=>'Scolpire pietra',
																						'description'=>' Plasma la pietra in qualsiasi forma.'),
																								19=>																							Array(
																							'name'=>'Tempesta di nevischio',
																							'description'=>' Ostacola la visione e il movimento.'),
																									20=>																								Array(
																								'name'=>'Veleno',
																								'description'=>' A contatto, infligge 1d3 danni a Cos a round per 6 round.'),
																										21=>																									Array(
																									'name'=>'Zanna magica superiore',
																									'description'=>' Un\'arma naturale del soggetto ottiene bonus +1 ai tiri per colpire e per i danni ogni 4 livelli (max +5).')),
						4=>																						Array(
						0=>					Array(
					'name'=>'Camminare nell\'aria',
					'description'=>' Il soggetto cammina nell\'aria come se fosse solida (sale a un\'angolazione di 45th).'),
							1=>						Array(
						'name'=>'Colpo infuocato',
						'description'=>' Colpisce i nemici con un fuoco divino (1d6 danni/livello).'),
								2=>							Array(
							'name'=>'Comandare vegetali',
							'description'=>' Influenza le azioni di una o pi&amp;ugrave; creature vegetali.'),
									3=>								Array(
								'name'=>'Controllare acqua',
								'description'=>' Solleva o abbassa masse d\'acqua.'),
										4=>									Array(
									'name'=>'Cura ferite gravi',
									'description'=>' Cura 3d8 danni +1/livello (max +15).'),
											5=>										Array(
										'name'=>'Dissolvi magie',
										'description'=>' Cancella un incantesimo o effetto magico.'),
												6=>											Array(
											'name'=>'Evoca alleato naturale IV',
											'description'=>' Richiama una creatura che combatte.'),
													7=>												Array(
												'name'=>'Guscio anti-vegetali',
												'description'=>' Mantiene a distanza i vegetali animati.'),
														8=>													Array(
													'name'=>'Inaridire',
													'description'=>' Fa appassire un vegetale o infligge 1d6 danni/livello a una creatura vegetale.'),
															9=>														Array(
														'name'=>'Libert&agrave; di movimento',
														'description'=>' Il soggetto si muove liberamente nonostante gli impedimenti.'),
																10=>															Array(
															'name'=>'Parassiti giganti',
															'description'=>' Trasforma millepiedi, scorpioni o ragni in parassiti giganti.'),
																	11=>																Array(
																'name'=>'Reincarnazione',
																'description'=>' Fa risorgere un morto in un corpo casuale.'),
																		12=>																	Array(
																	'name'=>'Respingere parassiti',
																	'description'=>' Insetti, ragni e altri parassiti rimangono a una distanza di 3 m.'),
																			13=>																		Array(
																		'name'=>'Rocce aguzze',
																		'description'=>' Le creature nell\'area subiscono 1d8 danni e possono essere rallentate.'),
																				14=>																			Array(
																			'name'=>'ScrutareF',
																			'description'=>' Spia soggetti a distanza.'),
																					15=>																				Array(
																				'name'=>'Stretta corrosiva',
																				'description'=>' Il proprio tocco corrode il ferro e le leghe metalliche.'),
																						16=>																					Array(
																					'name'=>'Tempesta di ghiaccio',
																					'description'=>' La grandine infligge 5d6 danni in un cilindro ampio 12 m.')),
							5=>																									Array(
							0=>						Array(
						'name'=>'Comunione con la natura',
						'description'=>' Si apprende com\'&amp;egrave; fatto il territorio nel raggio di 1,5 km/livello.'),
								1=>							Array(
							'name'=>'Controllare venti',
							'description'=>' Cambia la direzione e l\'intensit&amp;agrave; del vento.'),
									2=>								Array(
								'name'=>'Crescita animale',
								'description'=>' Un animale raddoppia la taglia.'),
										3=>									Array(
									'name'=>'Cura ferite critiche',
									'description'=>' Cura 4d8 danni +1/livello (max +20).'),
											4=>										Array(
										'name'=>'EspiazioneFM',
										'description'=>' Rimuove il fardello dei misfatti dal soggetto.'),
												5=>											Array(
											'name'=>'Evoca alleato naturale V',
											'description'=>' Richiama una creatura al proprio comando.'),
													6=>												Array(
												'name'=>'Interdizione alla morte',
												'description'=>' Concede immunit&amp;agrave; agli incantesimi di morte e agli effetti di energia negativa.'),
														7=>													Array(
													'name'=>'Invocare tempesta di fulmini',
													'description'=>' Come invocare il fulmine, ma 5d6 danni per fulmine.'),
															8=>														Array(
														'name'=>'Metamorfosi funesta',
														'description'=>' Trasforma il soggetto in un animale innocuo.'),
																9=>															Array(
															'name'=>'Muro di fuoco',
															'description'=>' Infligge 2d4 danni da fuoco fino a 3 m e 1d4 fino a 6 m. Attraversare il muro infligge 2d6 danni +1 danno/livello.'),
																	10=>																Array(
																'name'=>'Muro di spine',
																'description'=>' Le spine danneggiano chiunque tenti di passare.'),
																		11=>																	Array(
																	'name'=>'Pelle di pietraM',
																	'description'=>' Concede RD 10/adamantio.'),
																			12=>																		Array(
																		'name'=>'Piaga degli insetti',
																		'description'=>' Sciami di vespe attaccano le creature.'),
																				13=>																			Array(
																			'name'=>'ProfanareM',
																			'description'=>' Rende una locazione sacrilega.'),
																					14=>																				Array(
																				'name'=>'RisveglioM',
																				'description'=>' Un animale o un albero ottengono intelligenza umana.'),
																						15=>																					Array(
																					'name'=>'SantificareM',
																					'description'=>' Consacra una locazione.'),
																							16=>																						Array(
																						'name'=>'Traslazione arborea',
																						'description'=>' Si pu&amp;ograve; passare da un albero a un altro anche molto distante.'),
																								17=>																							Array(
																							'name'=>'Trasmutare fango in roccia',
																							'description'=>' Trasforma 2 cubi con spigolo di 3 m/livello.'),
																									18=>																								Array(
																								'name'=>'Trasmutare roccia in fango',
																								'description'=>' Trasforma 2 cubi con spigolo di 3 m/livello.')),
								6=>																									Array(
								0=>							Array(
							'name'=>'Bastone dell\'incantesimo',
							'description'=>' Infonde un incantesimo in un bastone ferrato di legno.'),
									1=>								Array(
								'name'=>'Cura ferite leggere di massa',
								'description'=>' Cura 1d8 danni +1/livello a 1 soggetto/livello.'),
										2=>									Array(
									'name'=>'Dissolvi magie superiore',
									'description'=>' Come dissolvi magie, ma con bersagli multipli.'),
											3=>										Array(
										'name'=>'Evoca alleato naturale VI',
										'description'=>' Richiama una creatura al proprio comando.'),
												4=>											Array(
											'name'=>'Forza del toro di massa',
											'description'=>' Come forza del toro, ma influenza 1 soggetto/livello.'),
													5=>												Array(
												'name'=>'Grazia del gatto di massa',
												'description'=>' Come grazia del gatto, ma influenza 1 soggetto/livello.'),
														6=>													Array(
													'name'=>'Guscio anti-vita',
													'description'=>' Un campo di 3 m respinge le creature viventi.'),
															7=>														Array(
														'name'=>'Legno di ferro',
														'description'=>' Il legno magico &amp;egrave; forte come l\'acciaio.'),
																8=>															Array(
															'name'=>'Muovere il terreno',
															'description'=>' Scava trincee e fa crescere colline.'),
																	9=>																Array(
																'name'=>'Muro di pietra',
																'description'=>' Crea un muro di pietra che pu&amp;ograve; essere plasmato.'),
																		10=>																	Array(
																	'name'=>'Pietre parlanti',
																	'description'=>' Permette di parlare con la pietra naturale o lavorata.'),
																			11=>																		Array(
																		'name'=>'Querciaviva',
																		'description'=>' Una quercia diventa un treant guardiano.'),
																				12=>																			Array(
																			'name'=>'Resistenza dell\'orso di massa',
																			'description'=>' Come resistenza dell\'orso, ma influenza 1 soggetto/livello.'),
																					13=>																				Array(
																				'name'=>'Respingere legno',
																				'description'=>' Respinge gli oggetti in legno.'),
																						14=>																					Array(
																					'name'=>'Saggezza del gufo di massa',
																					'description'=>' Come saggezza del gufo, ma influenza 1 soggetto/livello.'),
																							15=>																						Array(
																						'name'=>'Scopri il percorso',
																						'description'=>' Indica la via pi&amp;ugrave; diretta verso una locazione.'),
																								16=>																							Array(
																							'name'=>'Semi di fuoco',
																							'description'=>' Ghiande e bacche diventano bombe esplosive.'),
																									17=>																								Array(
																								'name'=>'Trasporto vegetale',
																								'description'=>' Ci si muove istantaneamente da una pianta all\'altra della stessa specie.')),
									7=>																					Array(
									0=>								Array(
								'name'=>'Animare vegetali',
								'description'=>' Anima uno o pi&amp;ugrave; alberi che attaccano a comando.'),
										1=>									Array(
									'name'=>'Bagliore solare',
									'description'=>' Il bagliore acceca e infligge 4d6 danni.'),
											2=>										Array(
										'name'=>'Camminare nel vento',
										'description'=>' Insieme ai propri alleati si diventa inconsistenti e si pu&amp;ograve; viaggiare velocemente.'),
												3=>											Array(
											'name'=>'Controllare tempo atmosferico',
											'description'=>' Cambia il tempo atmosferico in un\'area.'),
													4=>												Array(
												'name'=>'Cura ferite moderate di massa',
												'description'=>' Cura 2d8 danni +1/livello (max +30) a 1 soggetto/livello.'),
														5=>													Array(
													'name'=>'Evoca alleato naturale VII',
													'description'=>' Richiama una creatura al proprio comando.'),
															6=>														Array(
														'name'=>'Guarigione',
														'description'=>' Cura 10 danni/livello, tutte le malattie e le condizioni mentali.'),
																7=>															Array(
															'name'=>'Piaga strisciante',
															'description'=>' Sciami di millepiedi che attaccano a comando.'),
																	8=>																Array(
																'name'=>'Scrutare superiore',
																'description'=>' Come scrutare, ma pi&amp;ugrave; velocemente e a lungo.'),
																		9=>																	Array(
																	'name'=>'Tempesta di fuoco',
																	'description'=>' Infligge 1d6 danni da fuoco/livello.'),
																			10=>																		Array(
																		'name'=>'Trasforma bastone',
																		'description'=>' Il proprio bastone diventa un treant.'),
																				11=>																			Array(
																			'name'=>'Trasmutare metallo in legno',
																			'description'=>' Il metallo nel raggio di 12 m diventa legno.'),
																					12=>																				Array(
																				'name'=>'Visione del veroM',
																				'description'=>' Permette di vedere tutte le cose per quello che sono veramente.')),
										8=>																				Array(
										0=>									Array(
									'name'=>'Controllare vegetali',
									'description'=>' Controlla le azioni delle creature vegetali.'),
											1=>										Array(
										'name'=>'Cura ferite gravi di massa',
										'description'=>' Cura 3d8 danni +1/livello (max +35) a 1 soggetto/livello.'),
												2=>											Array(
											'name'=>'Dito della morte',
											'description'=>' Infligge 10 danni/livello a un soggetto.'),
													3=>												Array(
												'name'=>'Esplosione solare',
												'description'=>' Acceca tutti nel raggio di 24 m, infligge 6d6 danni.'),
														4=>													Array(
													'name'=>'Evoca alleato naturale VIII',
													'description'=>' Richiama una creatura al proprio comando.'),
															5=>														Array(
														'name'=>'Forme animali',
														'description'=>' 1 alleato/livello subisce metamorfosi nell\'animale scelto.'),
																6=>															Array(
															'name'=>'Inversione della gravit&agrave;',
															'description'=>' Gli oggetti e le creature cadono verso l\'alto.'),
																	7=>																Array(
																'name'=>'Parola del ritiro',
																'description'=>' Teletrasporta indietro ad un posto designato.'),
																		8=>																	Array(
																	'name'=>'Respingere metallo o pietra',
																	'description'=>' Respinge il metallo e la pietra.'),
																			9=>																		Array(
																		'name'=>'Terremoto',
																		'description'=>' Scossa tellurica in un raggio di 24 m.'),
																				10=>																			Array(
																			'name'=>'Turbine',
																			'description'=>' Un ciclone infligge danni e porta via creature.')),
											9=>																				Array(
											0=>										Array(
										'name'=>'Antipatia',
										'description'=>' L\'oggetto o la locazione influenzata respingono certe creature.'),
												1=>											Array(
											'name'=>'Cumulo strisciante',
											'description'=>' Evoca 1d4+2 cumuli striscianti che attaccano a comando.'),
													2=>												Array(
												'name'=>'Cura ferite critiche di massa',
												'description'=>' Cura 4d8 danni +1/livello (max +40) a molte creature.'),
														3=>													Array(
													'name'=>'Evoca alleato naturale IX',
													'description'=>' Richiama una creatura al proprio comando.'),
															4=>														Array(
														'name'=>'Previsione',
														'description'=>' Un &quot;sesto senso&quot; avverte di pericoli imminenti.'),
																5=>															Array(
															'name'=>'Rigenerazione',
															'description'=>' Gli arti recisi di un soggetto ricrescono, cura 4d8 danni +1/livello (max +35).'),
																	6=>																Array(
																'name'=>'Sciame elementale',
																'description'=>' Evoca molteplici elementali.'),
																		7=>																	Array(
																	'name'=>'SimpatiaM',
																	'description'=>' L\'oggetto o la locazione influenzata attraggono certe creature.'),
																			8=>																		Array(
																		'name'=>'Tempesta di vendetta',
																		'description'=>' Tempesta di pioggia acida, fulmini e grandine.'),
																				9=>																			Array(
																			'name'=>'TrasformazioneF',
																			'description'=>' Permette di trasformarsi in qualsiasi creatura e di cambiare forma una volta per round.'))); 
 echo json_encode($test); ?>