<?php 
 $test = 					Array(
		1=>																Array(
		0=>	Array(
	'name'=>'Arma magica',
	'description'=>' L\'arma ottiene bonus +1.'),
			1=>		Array(
		'name'=>'Benedire l\'acquaM',
		'description'=>' Rende l\'acqua santa.'),
				2=>			Array(
			'name'=>'Benedire un\'arma',
			'description'=>' L\'arma ottiene un colpo accurato contro i nemici malvagi.'),
					3=>				Array(
				'name'=>'Benedizione',
				'description'=>' Gli alleati ottengono bonus +1 ai tiri per colpire e +1 ai tiri salvezza contro paura.'),
						4=>					Array(
					'name'=>'Contrastare elementi',
					'description'=>' Si &amp;egrave; a proprio agio in un ambiente freddo o caldo.'),
							5=>						Array(
						'name'=>'Creare acqua',
						'description'=>' Crea 7,4 litri/livello di acqua pura.'),
								6=>							Array(
							'name'=>'Cura ferite leggere',
							'description'=>' Cura 1d8 danni +1/livello (max +5).'),
									7=>								Array(
								'name'=>'Favore divino',
								'description'=>' Si ottiene bonus +1 ogni 3 livelli ai tiri per colpire e per i danni.'),
										8=>									Array(
									'name'=>'Individuazione dei non morti',
									'description'=>' Rivela non morti nel raggio di 18 m.'),
											9=>										Array(
										'name'=>'Individuazione del veleno',
										'description'=>' Individua il veleno in una creatura o in un oggetto.'),
												10=>											Array(
											'name'=>'Lettura del magico',
											'description'=>' Per leggere pergamene e libri degli incantesimi.'),
													11=>												Array(
												'name'=>'Protezione dal caos/male',
												'description'=>' Bonus +2 alla CA e ai tiri salvezza; pi&amp;ugrave; protezione addizionale contro allineamento selezionato.'),
														12=>													Array(
													'name'=>'Resistenza',
													'description'=>' Il soggetto ottiene bonus +1 ai tiri salvezza.'),
															13=>														Array(
														'name'=>'Ristorare inferiore',
														'description'=>' Dissolve penalit&amp;agrave; magiche alle caratteristiche o cura 1d4 danni alle caratteristiche.'),
																14=>															Array(
															'name'=>'Virt&ugrave;',
															'description'=>' Il soggetto ottiene 1 pf temporaneo.')),
			2=>											Array(
			0=>		Array(
		'name'=>'Allineamento imperscrutabile',
		'description'=>' Nasconde l\'allineamento all\'individuazione magica per 24 ore.'),
				1=>			Array(
			'name'=>'Forza del toro',
			'description'=>' Bonus +4 a For per 1 minuto/livello.'),
					2=>				Array(
				'name'=>'Resistere all\'energia',
				'description'=>' Ignora 10 (o pi&amp;ugrave;) danni per ogni attacco da uno specifico tipo di energia.'),
						3=>					Array(
					'name'=>'Rimuovi paralisi',
					'description'=>' Libera una o pi&amp;ugrave; creature dalla paralisi o da un effetto di lentezza.'),
							4=>						Array(
						'name'=>'Ritarda veleno',
						'description'=>' Impedisce al veleno di nuocere al soggetto per 1 ora/livello.'),
								5=>							Array(
							'name'=>'Saggezza del gufo',
							'description'=>' Bonus +4 a Sag per 1 minuto/livello.'),
									6=>								Array(
								'name'=>'Scudo su altriF',
								'description'=>' Si subisce met&amp;agrave; dei danni destinati a un soggetto.'),
										7=>									Array(
									'name'=>'Splendore dell\'aquila',
									'description'=>' Bonus +4 a Car per 1 minuto/livello.'),
											8=>										Array(
										'name'=>'Zona di verit&agrave;',
										'description'=>' I soggetti all\'interno del raggio di azione non possono mentire.')),
				3=>													Array(
				0=>			Array(
			'name'=>'Arma magica superiore',
			'description'=>' Bonus +1 ogni 4 livelli (max +5).'),
					1=>				Array(
				'name'=>'Cerchio magico contro il caos/male',
				'description'=>' Come protezione dal male, ma ha un raggio di 3 m e una durata di 10 minuti/livello.'),
						2=>					Array(
					'name'=>'Cura ferite moderate',
					'description'=>' Cura 2d8 danni +1/livello (max +10).'),
							3=>						Array(
						'name'=>'Dissolvi magie',
						'description'=>' Cancella un incantesimo o effetto magico.'),
								4=>							Array(
							'name'=>'Guarire cavalcatura',
							'description'=>' Come guarigione su un cavallo o un\'altra cavalcatura speciale.'),
									5=>								Array(
								'name'=>'Luce diurna',
								'description'=>' Luce intensa nel raggio di 18 m.'),
										6=>									Array(
									'name'=>'Preghiera',
									'description'=>' Gli alleati ottengono bonus +1 alla maggior parte dei tiri, i nemici penalit&amp;agrave; -1.'),
											7=>										Array(
										'name'=>'Rimuovi cecit&agrave;/sordit&agrave;',
										'description'=>' Cura condizioni normali o magiche di cecit&amp;agrave; o sordit&amp;agrave;.'),
												8=>											Array(
											'name'=>'Rimuovi maledizione',
											'description'=>' Libera un oggetto o una persona da una maledizione.'),
													9=>												Array(
												'name'=>'Rivela bugie',
												'description'=>' Rivela le menzogne deliberate.')),
					4=>													Array(
					0=>				Array(
				'name'=>'Cura ferite gravi',
				'description'=>' Cura 3d8 danni +1/livello (max +15).'),
						1=>					Array(
					'name'=>'Dissolvi il caos',
					'description'=>' Bonus +4 contro gli attacchi delle creature caotiche.'),
							2=>						Array(
						'name'=>'Dissolvi il male',
						'description'=>' Bonus +4 contro gli attacchi delle creature malvagie.'),
								3=>							Array(
							'name'=>'Interdizione alla morte',
							'description'=>' Concede immunit&amp;agrave; agli incantesimi di morte e agli effetti di energia negativa.'),
									4=>								Array(
								'name'=>'Neutralizza veleno',
								'description'=>' Rende immune al veleno un soggetto, disintossica dal veleno in o su un soggetto.'),
										5=>									Array(
									'name'=>'RistorareM',
									'description'=>' Ripristina il risucchio di livelli e di punteggi di caratteristica.'),
											6=>										Array(
										'name'=>'Sigillo di giustizia',
										'description'=>' Determina un\'azione che attiver&amp;agrave; una maledizione sul soggetto.'),
												7=>											Array(
											'name'=>'Spada sacra',
											'description'=>' L\'arma diventa +5 e infligge +2d6 danni contro il male.'),
													8=>												Array(
												'name'=>'Spezzare incantamento',
												'description'=>' Libera i soggetti da ammaliamenti, alterazioni, maledizioni.'))); 
 echo json_encode($test); ?>