<?php 
 $test = 					Array(
		1=>																				Array(
		0=>	Array(
	'name'=>'Allarme',
	'description'=>' Sorveglia un\'area per 2 ore/livello.'),
			1=>		Array(
		'name'=>'Animale messaggero',
		'description'=>' Invia un animale Minuscolo in un posto specifico.'),
				2=>			Array(
			'name'=>'Calmare animali',
			'description'=>' Calma 2d4 + livello DV di animali.'),
					3=>				Array(
				'name'=>'Charme su animali',
				'description'=>' Rende un animale amichevole.'),
						4=>					Array(
					'name'=>'Contrastare elementi',
					'description'=>' Si &amp;egrave; a proprio agio in un ambiente freddo o caldo.'),
							5=>						Array(
						'name'=>'Evoca alleato naturale I',
						'description'=>' Richiama una creatura al proprio comando.'),
								6=>							Array(
							'name'=>'Individuazione del veleno',
							'description'=>' Individua il veleno in una creatura o in un oggetto.'),
									7=>								Array(
								'name'=>'Individuazione di animali o vegetali',
								'description'=>' Individua specie di animali o vegetali.'),
										8=>									Array(
									'name'=>'Individuazione di calappi e trabocchetti',
									'description'=>' Rivela trappole naturali o primitive.'),
											9=>										Array(
										'name'=>'Intralciare',
										'description'=>' Le piante avviluppano chiunque in un raggio di 12 m.'),
												10=>											Array(
											'name'=>'Lettura del magico',
											'description'=>' Per leggere pergamene e libri degli incantesimi.'),
													11=>												Array(
												'name'=>'Nascondersi agli animali',
												'description'=>' Gli animali non riescono a percepire 1 soggetto/livello.'),
														12=>													Array(
													'name'=>'Parlare con gli animali',
													'description'=>' Si pu&amp;ograve; comunicare con gli animali.'),
															13=>														Array(
														'name'=>'Passare senza tracce',
														'description'=>' 1 soggetto/livello non lascia tracce.'),
																14=>															Array(
															'name'=>'Passo veloce',
															'description'=>' Aumenta la propria velocit&amp;agrave; di 3 m.'),
																	15=>																Array(
																'name'=>'Resistere all\'energia',
																'description'=>' Ignora 10 (o pi&amp;ugrave;) danni per ogni attacco da uno specifico tipo di energia.'),
																		16=>																	Array(
																	'name'=>'Ritarda veleno',
																	'description'=>' Impedisce al veleno di nuocere al soggetto per 1 ora/livello.'),
																			17=>																		Array(
																		'name'=>'Saltare',
																		'description'=>' Il soggetto ottiene un bonus alle prove di Acrobazia.'),
																				18=>																			Array(
																			'name'=>'Zanna magica',
																			'description'=>' Un\'arma naturale del soggetto ottiene bonus +1 ai tiri per colpire e per i danni.')),
			2=>														Array(
			0=>		Array(
		'name'=>'Blocca animali',
		'description'=>' Paralizza un animale per 1 round/livello.'),
				1=>			Array(
			'name'=>'Calappio',
			'description'=>' Crea una trappola magica.'),
					2=>				Array(
				'name'=>'Crescita di spine',
				'description'=>' Le creature nell\'area subiscono 1d4 danni e possono essere rallentate.'),
						3=>					Array(
					'name'=>'Cura ferite leggere',
					'description'=>' Cura 1d8 danni +1/livello (max +5).'),
							4=>						Array(
						'name'=>'Evoca alleato naturale II',
						'description'=>' Richiama una creatura al proprio comando.'),
								5=>							Array(
							'name'=>'Grazia del gatto',
							'description'=>' Bonus +4 a Des per 1 minuto/livello.'),
									6=>								Array(
								'name'=>'Muro di vento',
								'description'=>' Respinge frecce, piccole creature e gas.'),
										7=>									Array(
									'name'=>'Parlare con i vegetali',
									'description'=>' Si pu&amp;ograve; comunicare con i vegetali normali e con le creature vegetali.'),
											8=>										Array(
										'name'=>'Pelle coriacea',
										'description'=>' Concede bonus di potenziamento +2 (o superiore) all\'armatura naturale.'),
												9=>											Array(
											'name'=>'Protezione dall\'energia',
											'description'=>' Assorbe 12 danni/livello da un tipo di energia.'),
													10=>												Array(
												'name'=>'Resistenza dell\'orso',
												'description'=>' Bonus +4 a Cos per 1 minuto/livello.'),
														11=>													Array(
													'name'=>'Saggezza del gufo',
													'description'=>' Bonus +4 a Sag per 1 minuto/livello.')),
				3=>																Array(
				0=>			Array(
			'name'=>'Camminare sull\'acqua',
			'description'=>' Il soggetto cammina sull\'acqua come se fosse solida.'),
					1=>				Array(
				'name'=>'Comandare vegetali',
				'description'=>' Influenza le azioni di una o pi&amp;ugrave; creature vegetali.'),
						2=>					Array(
					'name'=>'Crescita vegetale',
					'description'=>' Fa crescere la vegetazione e migliora i raccolti.'),
							3=>						Array(
						'name'=>'Cura ferite moderate',
						'description'=>' Cura 2d8 danni +1/livello (max +10).'),
								4=>							Array(
							'name'=>'Evoca alleato naturale III',
							'description'=>' Richiama una creatura al proprio comando.'),
									5=>								Array(
								'name'=>'Forma arborea',
								'description'=>' Si assume l\'aspetto di un albero per 1 ora/livello.'),
										6=>									Array(
									'name'=>'Neutralizza veleno',
									'description'=>' Rende immune al veleno un soggetto, disintossica dal veleno in o su un soggetto.'),
											7=>										Array(
										'name'=>'Respingere parassiti',
										'description'=>' Insetti, ragni e altri parassiti rimangono a una distanza di 3 m.'),
												8=>											Array(
											'name'=>'Ridurre animali',
											'description'=>' Rimpicciolisce un animale consenziente.'),
													9=>												Array(
												'name'=>'Rimpicciolire vegetali',
												'description'=>' Riduce la taglia o inaridisce la crescita dei vegetali naturali.'),
														10=>													Array(
													'name'=>'Rimuovi malattia',
													'description'=>' Cura tutte le malattie che affliggono il soggetto.'),
															11=>														Array(
														'name'=>'Scurovisione',
														'description'=>' Permette di vedere fino a 18 m nel buio totale.'),
																12=>															Array(
															'name'=>'Zanna magica superiore',
															'description'=>' Un\'arma naturale del soggetto ottiene bonus +1 ai tiri per colpire e per i danni ogni 4 livelli (max +5).')),
					4=>											Array(
					0=>				Array(
				'name'=>'Anti-individuazioneM',
				'description'=>' Nasconde il soggetto a divinazione e scrutamento.'),
						1=>					Array(
					'name'=>'Comunione con la natura',
					'description'=>' Si apprende com\'&amp;egrave; fatto il territorio nel raggio di 1,5 km/livello.'),
							2=>						Array(
						'name'=>'Crescita animale',
						'description'=>' Un animale raddoppia la taglia.'),
								3=>							Array(
							'name'=>'Cura ferite gravi',
							'description'=>' Cura 3d8 danni +1/livello (max +15).'),
									4=>								Array(
								'name'=>'Evoca alleato naturale IV',
								'description'=>' Richiama una creatura al proprio comando.'),
										5=>									Array(
									'name'=>'Libert&agrave; di movimento',
									'description'=>' Il soggetto si muove liberamente nonostante gli impedimenti.'),
											6=>										Array(
										'name'=>'Traslazione arborea',
										'description'=>' Si pu&amp;ograve; passare da un albero a un altro anche molto distante.'))); 
 echo json_encode($test); ?>